CREATE TABLE APARTAMENTOS_COMPARTIDOS (
ID NUMBER NOT NULL,
PERSONAS_VIVIENDO NUMBER NOT NULL,
CONSTRAINT PK_APACOMP PRIMARY KEY (ID),
CONSTRAINT FK_APAR_COMP_OPERADOR FOREIGN KEY (ID) REFERENCES OPERADORES(ID)
);

ALTER TABLE APARTAMENTOS_COMPARTIDOS ADD(
TIENE_MUEBLES NUMBER(1,0) DEFAULT 0,
CONSTRAINT CK_MUEBLES_APARTAMENTO CHECK (TIENE_MUEBLES = 1 OR TIENE_MUEBLES = 0)

);