CREATE TABLE HOTEL (
ID NUMBER NOT NULL, 
COD_INTEND NUMBER NOT NULL, 
TIPO NUMBER NOT NULL,
CAPACIDAD NUMBER NOT NULL, 
TAMANIO NUMBER NOT NULL,
CONSTRAINT PK_HAB_HOT PRIMARY KEY (ID),
CONSTRAINT FK_HABHOT_OPERADOR FOREIGN KEY (ID) REFERENCES OPERADORES(ID),
CONSTRAINT CK_TIPO CHECK ( TIPO = 1 OR TIPO = 2 OR TIPO = 3)

);