SELECT ID1, SUM1, SUM2 
FROM 
    (SELECT ID_OPERADOR ID1, SUM(PAGADO) SUM1
    FROM OPERADORES, FACTURAS 
    WHERE ID_OPERADOR = OPERADORES.ID 
    AND EXTRACT (YEAR FROM FECHA_ULTIMO_PAGO) = 1997
    GROUP BY ID_OPERADOR), 
    (SELECT ID_OPERADOR ID2, SUM(PAGADO) SUM2 
    FROM OPERADORES, FACTURAS 
    WHERE ID_OPERADOR = OPERADORES.ID 
    AND EXTRACT (YEAR FROM FECHA_ULTIMO_PAGO) = 1996
    GROUP BY ID_OPERADOR) 
WHERE ID1 = ID2;



DELETE FROM FACTURAS;

SELECT OP.* FROM OPERADORES OP, PROPUESTAS PR WHERE PR.ID_OPERADOR = OP.ID;

SELECT MAX(ID) FROM FACTURAS;



INSERT INTO FACTURAS(ID_CLIENTE, ID, FECHA_CREACION, ID_OPERADOR, CONCEPTO) VALUES (2, 0, TO_DATE('1997-12-23', 'yyyy-mm-dd'), 3, 'HOLIII');
COMMIT;