SELECT ID1, SUM1, SUM2 
FROM 
    (SELECT ID_OPERADOR ID1, SUM(PAGADO) SUM1
    FROM OPERADORES LEFT OUTER JOIN FACTURAS 
    ON ID_OPERADOR = OPERADORES.ID 
    WHERE EXTRACT (YEAR FROM FECHA_ULTIMO_PAGO) = 2018
    GROUP BY ID_OPERADOR) FULL OUTER JOIN
    (SELECT ID_OPERADOR ID2, SUM(PAGADO) SUM2 
    FROM OPERADORES LEFT OUTER JOIN FACTURAS 
    ON ID_OPERADOR = OPERADORES.ID 
    WHERE EXTRACT (YEAR FROM FECHA_ULTIMO_PAGO) = 2017
    GROUP BY ID_OPERADOR) 
ON ID1 = ID2;

SELECT OP.ID, SUM(TOTA.PAG1) SUM1, SUM(TOTA.PAG2) SUM2 
FROM OPERADORES OP 
LEFT OUTER JOIN
(SELECT FA1.ID_OPERADOR ID1, FA1.PAGADO PAG1, FA2.PAGADO PAG2 
FROM 
(SELECT * FROM FACTURAS WHERE EXTRACT (YEAR FROM FECHA_ULTIMO_PAGO) = 2018) FA1
FULL OUTER JOIN 
(SELECT * FROM FACTURAS WHERE EXTRACT (YEAR FROM FECHA_ULTIMO_PAGO) = 2017) FA2
ON FA1.ID_OPERADOR = FA2.ID_OPERADOR) TOTA
ON OP.ID = TOTA.ID1
GROUP BY OP.ID;

SELECT OP.ID, SUM(TOTA.PAG1) SUM1, SUM(TOTA.PAG2) SUM2 FROM OPERADORES OP LEFT OUTER JOIN (SELECT FA1.ID_OPERADOR ID1, FA1.PAGADO PAG1, FA2.PAGADO PAG2 FROM (SELECT * FROM FACTURAS WHERE EXTRACT (YEAR FROM FECHA_ULTIMO_PAGO) = 2018) FA1 FULL OUTER JOIN (SELECT * FROM FACTURAS WHERE EXTRACT (YEAR FROM FECHA_ULTIMO_PAGO) = 2017) FA2 ON FA1.ID_OPERADOR = FA2.ID_OPERADOR) TOTA ON OP.ID = TOTA.ID1 GROUP BY OP.ID;
    
    
SELECT OP.ID, SUM(TOTA.PAG1) SUM1, SUM(TOTA.PAG2) SUM2 FROM OPERADORES OP LEFT OUTER JOIN (SELECT FA1.ID_OPERADOR ID1, FA1.PAGADO PAG1, FA2.PAGADO PAG2 FROM (SELECT * FROM FACTURAS WHERE EXTRACT (YEAR FROM FECHA_ULTIMO_PAGO) = 2018) FA1 FULL OUTER JOIN (SELECT * FROM FACTURAS WHERE EXTRACT (YEAR FROM FECHA_ULTIMO_PAGO) = 2017) FA2 ON FA1.ID_OPERADOR = FA2.ID_OPERADOR) TOTA ON OP.ID = TOTA.ID1 GROUP BY OP.ID;

SELECT * FROM OPERADORES OP LEFT OUTER JOIN (SELECT ID_OPERADOR ID1, SUM(PAGADO) SUM1
    FROM OPERADORES LEFT OUTER JOIN FACTURAS 
    ON OPERADORES.ID = ID_OPERADOR
    WHERE EXTRACT (YEAR FROM FECHA_ULTIMO_PAGO) = 2018
    GROUP BY ID_OPERADOR) ON OP.ID = ID1;




SELECT * FROM OPERADORES;

DELETE FROM FACTURAS WHERE ID = 0;

SELECT OP.* FROM OPERADORES OP, PROPUESTAS PR WHERE PR.ID_OPERADOR = OP.ID;

SELECT MAX(ID) FROM FACTURAS;


SELECT * FROM RESERVAS;
SELECT * FROM RESERVAS, FACTURAS WHERE FACTURAS.ID = ID_FACTURA;
SELECT * FROM FACTURAS;
SELECT * FROM PROPUESTAS;
SELECT * FROM CLIENTES;


INSERT INTO FACTURAS(ID_CLIENTE, ID, FECHA_CREACION, ID_OPERADOR, CONCEPTO, FECHA_ULTIMO_PAGO) 
VALUES (2, 0, TO_DATE('1997-12-23', 'yyyy-mm-dd'), 3, 'HOLIII', TO_DATE('1997-12-23', 'yyyy-mm-dd'));
COMMIT;

SELECT po.id, po.nombre, po.tipo, po.costo, po.DIAS_CANCELACION ,COUNT(*) as cont FROM
RESERVAS Re, propuestas po
where Re.ID_PROPUESTA=po.ID
group by po.id, po.nombre, po.tipo, po.costo, po.DIAS_CANCELACION
order BY cont desc fetch first 20 rows only;

