SELECT AA1.ID1 ID_ALOJAMIENTO, (100/AA1.CONTFIN)*AA1.CONTFIN - (100/AA1.CONTFIN)*AA2.CONTFIN TASA FROM
(SELECT PR.ID ID1, COALESCE(PR2.CONT, 0) CONTFIN FROM PROPUESTAS PR LEFT OUTER JOIN 
(SELECT ID_OPERADOR, TIPO, COUNT(PR.ID) CONT FROM PROPUESTAS PR GROUP BY ID_OPERADOR, TIPO) PR2
ON PR.TIPO = PR2.TIPO AND PR.ID_OPERADOR = PR2.ID_OPERADOR) AA1, 
(SELECT PR.ID ID1, COALESCE(PR2.CONT, 0) CONTFIN FROM PROPUESTAS PR LEFT OUTER JOIN 
(SELECT ID_OPERADOR, TIPO, COUNT(PR.ID) CONT FROM PROPUESTAS PR, RESERVAS WHERE ID_PROPUESTA = PR.ID GROUP BY ID_OPERADOR, TIPO) PR2
ON PR.TIPO = PR2.TIPO AND PR.ID_OPERADOR = PR2.ID_OPERADOR) AA2
WHERE AA1.ID1 = AA2.ID1;