CREATE TABLE VECINOS (
ID NUMBER NOT NULL, 
NUM_HABITACIONES NUMBER NOT NULL, 
UBICACION VARCHAR2(40 BYTE) NOT NULL,
CARACT_SEGURO VARCHAR2(255 BYTE) NOT NULL,
CONSTRAINT NUM_MAYOR_CERO CHECK (NUM_HABITACIONES >= 0)
);