CREATE TABLE VIVIEN_UNI (
ID NUMBER NOT NULL, 
PRECIO_AD_SALA_ESTUDIO NUMBER DEFAULT 0,
PRECIO_AD_GYM NUMBER DEFAULT 0,
PRECIO_AD_SALA_ESPARC NUMBER DEFAULT 0, 
PRECIO_AD_REST NUMBER DEFAULT 0,
CONSTRAINT PK_VIVIENDA PRIMARY KEY (ID),
CONSTRAINT FK_OPERADORVIVIENDA FOREIGN KEY (ID) REFERENCES OPERADORES(ID),
CONSTRAINT CK_PRECIO_SALAEST_VIVUNI CHECK (PRECIO_AD_SALA_ESTUDIO >= 0),
CONSTRAINT CK_PRECIO_GYM_VIVUNI CHECK (PRECIO_AD_GYM >= 0),
CONSTRAINT CK_PRECIO_SALAESP_VIVUNI CHECK (PRECIO_AD_SALA_ESPARC >= 0),
CONSTRAINT CK_PRECIO_REST_VIVUNI CHECK (PRECIO_AD_REST >= 0)
);
